### ISSUE TITLE
.github/configs/draft-release.yml is not found.

### ISSUE THREAD

**Issue by hans-d** [cloudposse/.github#41]
[auto-release](https://github.com/cloudposse/.github/actions/runs/8118576615/job/22193063700#step:2:114)
cloudposse/.github: Invalid config file
{
  name: 'event',
  id: '8118576615',
  stack: 'Error: Configuration file .github/configs/draft-release.yml is not found. The configuration file must reside in your default branch.\n' +
    '    at getConfig (/home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:142745:13)\n' +
    '    at async drafter (/home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:142339:20)\n' +
    '    at async Promise.all (index 0)',
  type: 'Error'
}

**Comment by osterman** [comment]
This is resolved by moving to our updated shared workflows. 
- #51 
- #57
