### ISSUE TITLE
 Please update the following actions to use Node.js 20: release-drafter/release-drafter@v5.

### ISSUE THREAD

**Issue by hans-d** [cloudposse/.github#42]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: release-drafter/release-drafter@v5.

**Comment by hans-d** [comment]
need to check the renovatebot config

**Comment by osterman** [comment]
@hans-d I believe this should now be completed. We've upgraded almost all repos, with exception of a few that we're tracking separately.
